name: Run Notebook Weekly

on:
  schedule:
    - cron: '0 7 * * 1'  # Every Monday at 07:00 UTC
  workflow_dispatch:     # Allow manual triggering

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert

    - name: Execute notebook and convert to HTML
      run: |
        jupyter nbconvert --to html --execute analysis.ipynb --output index.html

    - name: Commit and push HTML output
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add index.html
        git commit -m "Automated weekly update of notebook output [skip ci]" || echo "No changes to commit"
        git push
