name: Run Notebook Weekly

on:
  schedule:
    - cron: '0 7 * * 1'  # Runs every Monday at 07:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert

    - name: Run Jupyter notebook
      run: |
        jupyter nbconvert --to html --execute analysis.ipynb --output index.html

    - name: Commit results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add index.html
        git commit -m "Update index.html [skip ci]" || echo "No changes to commit"
        git push
